# Generated by Django 4.0.1 on 2022-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_url', models.CharField(max_length=200, verbose_name='房源url')),
                ('house_title', models.CharField(max_length=100, verbose_name='房源名称')),
                ('house_area', models.FloatField(verbose_name='面积')),
                ('house_floor', models.CharField(max_length=10, verbose_name='楼层（6/6楼）')),
                ('house_model', models.CharField(max_length=10, verbose_name='户型（3^1：三室一厅）')),
                ('house_traffic', models.CharField(max_length=200, verbose_name='离附近交通位置')),
                ('house_subway', models.CharField(max_length=200, verbose_name='所属地铁范围')),
                ('house_geocode', models.CharField(max_length=50, verbose_name='小区所在经纬度')),
                ('house_price', models.IntegerField(verbose_name='价格')),
                ('house_rent', models.CharField(max_length=20, verbose_name='租赁方式(合租、整租)')),
            ],
            options={
                'db_table': 'search_house',
            },
        ),
    ]
