# Generated by Django 4.0.1 on 2022-03-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'managed': True},
        ),
    ]
