# Generated by Django 4.0.1 on 2022-03-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_house_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'managed': False},
        ),
    ]
